[tool.poetry]
name = "flask-sorteio"
version = "0.1.0"
description = "Uma aplicação Flask para distribuição de cotas."
authors = ["Erik Marques <lucro.alternativo@outlook.com>"]
readme = "./flask_sorteio/README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.1.0"
flask-sqlalchemy = "^3.1.1"
dynaconf = "^3.2.7"

[tool.taskipy.variables]
cur_dir = '/c/Users/Estudos/Documents/flask-app'

[tool.taskipy.tasks]
cwd = { cmd='cd {cur_dir}', help='muda para o diretorio de trabalho no terminal(bash)' }
cmd_test = { cmd='python -m pytest tests/', help='roda os testes' }
test = { cmd='task cwd && task cmd_test', help='muda para o diretorio de trabalho e executa os testes' }

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
flask-pytest = "^0.0.5"
flask-migrate = "^4.1.0"
flask-shell-ipython = "^0.5.3"
flask-debugtoolbar = "^0.16.0"
taskipy = "^1.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
